### ISSUE TITLE
unable to login to airflow

### ISSUE THREAD

**Issue by Jalen-Foreman** [LinkedInLearning/hands-on-introduction-data-engineering-4395021#1]
When I try to login to airflow with the give credentials, I get "BAD REQUEST, the referrer does not match the host". I looked some things online and it has something to do with the request not receiving my headers.

**Comment by ashulakhwan** [comment]
Same issue persists with me

**Comment by vinooganesh** [comment]
Hi @Jalen-Foreman and @ashulakhwan - You will need to follow the instructions at 2 min 50 sec in the Installing Airflow video: https://www.linkedin.com/learning/hands-on-introduction-data-engineering/installing-airflow?resume=false to resolve this issue. 

You can see the full list of steps here: https://github.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/blob/main/install_and_run_airflow.sh. Specifically, this line: https://github.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/blob/main/install_and_run_airflow.sh#L11 contains the change that you need to make to get things working.

**Comment by clingrodvon** [comment]
Hi @vinooganesh . I just keep getting invalid login/password.  I have redone the "airflow users create \  four times and it says that it added my username with role,  but still no luck logging in.   That change to "false" in install_and_run_airflow.sh  is already correct.

**Comment by vinooganesh** [comment]
@clingrodvon what is the username and password combination you are using?

**Comment by clingrodvon** [comment]
admin9,  WordPass2Sent from my iPhoneOn Sep 4, 2023, at 4:08 PM, Vinoo Ganesh ***@***.***> wrote:﻿
@clingrodvon what is the username and password combination you are using?

**Comment by vinooganesh** [comment]
I'm not sure where you are getting those login details. If you follow this command: https://github.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/blob/main/install_and_run_airflow.sh#L18, it will create a user with the username `admin` and the password `password`. Could you try creating a user this way?

**Comment by clingrodvon** [comment]
Vinoo,  thanks for the quick reply .  I will let you know as soon as I have a chance to try that.Sent from my iPhoneOn Sep 4, 2023, at 4:36 PM, Vinoo Ganesh ***@***.***> wrote:﻿
I'm not sure where you are getting those login details. If you follow this command: https://github.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/blob/main/install_and_run_airflow.sh#L18, it will create a user with the username admin and the password password. Could you try creating a user this way?

**Comment by clingrodvon** [comment]
Vinoo, Now I get Bad Request.

**Comment by vinooganesh** [comment]
You should be able to follow the instructions here to resolve the issue: https://github.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/issues/1#issuecomment-1633013856

**Comment by clingrodvon** [comment]
BTW,  originally I used all the same generic user information, but it seems like it kept giving me “already exists” replies. So I tried to make the credentials unique enough to not run into that.  So now  I’m just getting the Bad Request msg with those credentials you recommended.Sent from my iPhoneOn Sep 4, 2023, at 9:14 PM, Vinoo Ganesh ***@***.***> wrote:﻿
You should be able to follow the instructions here to resolve the issue: #1 (comment)
