### ISSUE TITLE
Apache Airflow Installation

### ISSUE THREAD

**Issue by EdwinC2021** [LinkedInLearning/hands-on-introduction-data-engineering-4395021#5]
The installation process seems to be advanced despite the process taken in the video the github did not provide the guide to the video 2.2 and I was totally lost, played the video several, days and not seem to be getting headway for the installation

**Comment by DataGuru-London** [comment]
Same issues. It needs some explaining for sure.

**Comment by preetijain92** [comment]
Same Issue Here

**Comment by vinooganesh** [comment]
Some of these instructions were cut as part of the editorial process. There will be an updated set of videos that should clarify this that will be published in the coming weeks.
