### ISSUE TITLE
Cant open the airflow webserver 

### ISSUE THREAD

**Issue by PaintedW0lf** [LinkedInLearning/hands-on-introduction-data-engineering-4395021#8]
## Issue Overview
 I am having issues opening the airflow webserver. 

## Describe your environment

First of all cant run the airflow webserver -D command in 02-03 . But if i run the same command in 02-02. I can use the ports. 

## Steps to Reproduce

1. Linkedin learning course for hands-on-introduction-data-engineering-4395021/airflow
2.
3.
4.

## Expected Behavior
 Airflow login page 

## Current Behavior
 
<img width="675" alt="image" src="https://github.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/assets/97552907/2d6b65fa-ef8e-4d55-a5ee-0beca655e886">

**Comment by vinooganesh** [comment]
Transient issue, this works as expected
