### ISSUE TITLE
Airflow job DAG script for Data load is not in github repo.

### ISSUE THREAD

**Issue by ibozkurt79** [LinkedInLearning/hands-on-introduction-data-engineering-4395021#9]
## Issue Overview
Airflow job DAG script for Data load is not in github repo. #9
Need scripts of airflow DAG to replicate learning environment. LAB has no files in github

## Describe your environment
N/A

## Steps to Reproduce

1.
2.
3.
4.

**Comment by vinooganesh** [comment]
@ibozkurt79 the files should be there (many others have completed the course). Please feel free to reopen this issue if you are still having issues.
